#!/bin/bash

# prepare info file
INFO_FILE_DIR="/tmp/jenkins-upgrade"
INFO_FILE="plugins.update.info"
TOKEN="@/var/lib/jenkins/.administrative-token"

mkdir -p $INFO_FILE_DIR
# get current version of cli JAR
cd $INFO_FILE_DIR
rm -f jenkins-cli.jar
wget http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar

PLUGIN_LIST="$(java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ list-plugins)"

java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ install-plugin $(echo "$PLUGIN_LIST"|awk '{print $1}'|xargs)

java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ quiet-down -block -timeout 3600000
apt-get update
systemctl stop jenkins
apt-get install jenkins
systemctl start jenkins
java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ version


