#!/bin/bash

sendStatus(){
    local STATUS="$1"
    echo ">>>>$STATUS<<<<"
    logger -t "jenkins-unattended-upgrades" "$STATUS"
    if (which zabbix_sender &>/dev/null);then
      zabbix_sender -s `hostname` -c /etc/zabbix/zabbix_agentd.conf -k jenkins.jenkins-unattended-upgrades -o "$STATUS" > /dev/null
    fi
}


# prepare info file
INFO_FILE_DIR="/usr/share/jenkins"
TOKEN="/etc/jenkins/admin-password"

if (! [ -f "$TOKEN" ] );then
    echo "ERROR: no such file $TOKEN"
    exit 1
fi

mkdir -p $INFO_FILE_DIR
# get current version of cli JAR

cd $INFO_FILE_DIR

if ( ! [ -f "jenkins-cli.jar" ] );then
    unzip -j -o /usr/share/jenkins/jenkins.war WEB-INF/jenkins-cli.jar
fi

SUCCESS_JENKINS="false"
PLUGIN_LIST="$(java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ list-plugins)"

echo "INFO: invoking plugin upgrades"
echo
echo "$PLUGIN_LIST"
java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ install-plugin $(echo "$PLUGIN_LIST"|awk '{print $1}'|xargs)

echo "INFO: blocking jenkins"
java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ quiet-down -block -timeout 3600000
apt-get update
echo "INFO: shutdown and upgrade"
systemctl stop jenkins docker
apt-get install jenkins docker-ce
unzip -j -o /usr/share/jenkins/jenkins.war WEB-INF/jenkins-cli.jar
systemctl start jenkins


RES=""
for i in `seq 1 10`; do
  sleep 30
  echo "waiting for jenkins to be back after restart"
  RES="$(java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ version 2>&1)"
  if [ "$?" = "0" ];then
      SUCCESS_JENKINS="true"
      break
  fi
done

SUCCESS_DOCKER="false"
if (docker run hello-world|grep -q "Hello from Docker");then
  SUCCESS_DOCKER="true"
fi

if [ "$SUCCESS_JENKINS" = "true" ] && [ "$SUCCESS_DOCKER" = "true" ] ;then
   sendStatus "OK: UPGRADE $RES WAS SUCCESSFUL"
   exit 0
else
   sendStatus "ERROR: UPGRADE WAS NOT SUCCESSFUL"
   exit 1
fi
