#!/bin/bash

# prepare info file
INFO_FILE_DIR="/usr/share/jenkins"
TOKEN="/etc/jenkins/admin-password"

if (! [ -f "$TOKEN" ] );then
    echo "ERROR: no such file $TOKEN"
    exit 1
fi

mkdir -p $INFO_FILE_DIR
# get current version of cli JAR

cd $INFO_FILE_DIR

if ( ! [ -f "jenkins-cli.jar" ] );then
    unzip -j -o /usr/share/jenkins/jenkins.war WEB-INF/jenkins-cli.jar
fi

SUCCESS="false"
PLUGIN_LIST="$(java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ list-plugins)"

echo "INFO: invoking plugin upgrades"
echo
echo "$PLUGIN_LIST"
java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ install-plugin $(echo "$PLUGIN_LIST"|awk '{print $1}'|xargs)
if [ "$?" = "0" ];then
  SUCCESS="true"
  break
fi

if (apt-get -u upgrade -s|grep -q " jenkins ");then
    echo "INFO: update for jenkins itself available, upgrading"
    java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ quiet-down -block -timeout 3600000
    apt-get update
    systemctl stop jenkins
    apt-get install jenkins
    unzip -j -o /usr/share/jenkins/jenkins.war WEB-INF/jenkins-cli.jar
    systemctl start jenkins


    RES=""
    for i in `seq 1 10`; do
      sleep 30
      echo "waiting for jenkins to be back"
      RES="$(java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ version 2>&1)"
      if [ "$?" = "0" ];then
          SUCCESS="true"
          break
      fi
    done
fi

if [ "$SUCCESS" = "true" ];then
   echo "UPGRADE $RES WAS SUCCESSFUL"
   exit 0
else
   echo "UPGRADE WAS NOT SUCCESSFUL"
   exit 1
fi
